import { z } from 'zod';
import { users } from '../db/users.schema';
import { createInsertSchema, createSelectSchema, createUpdateSchema } from 'drizzle-zod';

// Create Zod schemas from the Drizzle users schema
export const userInsertSchema = createInsertSchema(users);
export const userSelectSchema = createSelectSchema(users);
export const userUpdateSchema = createUpdateSchema(users);


export const AuthRegSchema = createInsertSchema(users, {
  email: z.email("Invalid email address"),
  pass: z.string().min(8, "Password too short").max(125),
})
  .extend({
    passConfirm: z.string(),
  })
  .omit({
    id: true,   // Generated by DB
    slug: true, // Generated by Backend
  })
  .superRefine(({ pass, passConfirm }, ctx) => {
    if (passConfirm !== pass) {
      ctx.addIssue({
        code: "custom",
        message: "Passwords do not match",
        path: ["passConfirm"],
      });
    }
  });

export type  AuthRegType = z.infer<typeof AuthRegSchema>;


export const AuthLoginSchema = z.object({
  email: z.email().nonempty("Email is required"),
  pass: z.string().min(8, "Password is required"),
});

export type AuthLoginType = z.infer<typeof AuthLoginSchema>;

export const AuthLogoutSchema = z.object({
  pass: z.string().min(8, "Password is required"),
});

export type AuthLogoutType = z.infer<typeof AuthLogoutSchema>;


export const ProfileSchema = z.object({
  oldPass: z.string().min(8, "Password is required"),
  pass: z.string().min(8, "Password is required"),
  passConfirm: z.string(),
}).superRefine(({ pass, passConfirm }, ctx) => {
  if (passConfirm !== pass) {
    ctx.addIssue({
      code: "custom",
      message: "Passwords do not match",
      path: ["userPassConfirm"],
    });
  }
});

export type  ProfileType = z.infer<typeof ProfileSchema>;

// Additional schemas for profile updates
export const ProfileUpdateEmailSchema = z.object({
  email: z.email("Invalid email address"),
  pass: z.string().min(8, "Password is required"),
});

export const ProfileUpdatePasswordSchema = z.object({
  oldPass: z.string().min(8, "Current password is required"),
  pass: z.string().min(8, "New password is required"),
  passConfirm: z.string(),
}).superRefine(({ pass, passConfirm }, ctx) => {
  if (passConfirm !== pass) {
    ctx.addIssue({
      code: "custom",
      message: "Passwords do not match",
      path: ["pass_confirm"],
    });
  }
});

export const ProfileDeleteAccountSchema = z.object({
  pass: z.string().min(8, "Password is required"),
});


