[build.environment]
  NODE_VERSION = "20"

[build]
  base = "server"
  publish = "server/build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http", "body-parser", "dotenv", "cors", "helmet", "compression", "method-override", "cookie-parser", "pg-hstore", "pg"]
  directory = "netlify/functions"


[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api"
status = 200

[[redirects]]
  from = "/"
  to = "/api"
  status = 301


[dev]
  host = "$SERVER_DEV_HOST"
  port = 8888